# Generated by Django 2.1.3 on 2019-10-12 14:28

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191012_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prntphno',
            field=phone_field.models.PhoneField(blank='True', help_text='Contact parent phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='student',
            name='studphno',
            field=phone_field.models.PhoneField(blank='True', help_text='Contact student phone number', max_length=31),
        ),
    ]
